### ISSUE TITLE
No guards in Undercity

### ISSUE THREAD

**Issue by Iazneznam** [FireFly-WoW/FireFly-IssueTracker#152] opened 2017-04-30 16:10 UTC
Thats it, there are no guards in Undercity from which you can ask for directions.

**Comment by TW3TY** [comment] 2017-04-30 16:24
> Not a single **Kor'kron Overseer** ? @Iazneznam

**Comment by Iazneznam** [comment] 2017-04-30 17:16
Nope only the Royal guard but they dont give directions.

**Comment by JunkyBulgaria** [comment] 2017-05-01 13:00
kor'kron overseers were added in 3.3x after undercity attack

**Comment by JunkyBulgaria** [comment] 2017-05-01 21:59
closed as it works as intended (part of the progressive content) please make new issue with information about the old guards

**Closed by JunkyBulgaria** 2017-05-01 21:59 UTC
