### ISSUE TITLE
Quest: The Drakkensryd

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#473] opened 2017-06-06 16:34 UTC
**Description:**

When riding on a dragon most of the time you are out of range on your abilities

**Current behaviour:**

You can autoattack, but your abilities are rarely working

**Expected behaviour:**

You should be able to use all your abilities

**Steps to reproduce the problem:**

Get the quest The Drakkensryd
2. get close to a Hyldsmeet Drakerider
3. See how almost only auto attack works.

Note: At the end of the quest, the dragon does not fly up to thorim, you have to unlick the mount and fly up yourself.

**Screenshots:**

http://imgur.com/a/KED24

**Comment by Siderbas** [comment] 2017-06-06 17:02
Duplicate of #274, please use the search function - thank you.

**Closed by Siderbas** 2017-06-06 17:02 UTC
Labels: Duplicate

**Comment by thestranger064** [comment] 2017-06-06 17:14
I did use the search - but typed in only drakk , thought that was enough. appareantly if you dont type Drakkensryd you will not be able to find it.

**Comment by Siderbas** [comment] 2017-06-06 17:15
np at all, thank you for using our bugtracker and for reporting all this!

**Comment by thestranger064** [comment] 2017-06-06 17:16
Nps I hope more ppl help out finding bugs!
