### ISSUE TITLE
Dungeon: Zul'Farrak -  Pyramid Event is not working properly

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#13] opened 2017-04-14 01:05 UTC
**Description:**

 Pyramid Event is not working properly

**Current behaviour:**

* Soon as you kill all mobs under the Pyramid the npc you rescued stay on the top of the pyramid doing nothing for a while. After like 2 min they go downstair and everything works fine except of the delay and the fact that mobs under pyramid get respowned already and they starting to fight with them again.  

**Expected behaviour:**

* Once you all kill mobs under the pyramid the npc you rescued are supposed to come down under the pyramid so you can talk to them and have fight with them.

**Comment by JunkyBulgaria** [comment] 2017-04-15 14:29
Works as intended,  just tried it. Once you kill the boss and you free the prisoners they are walking to their positions in front of the cages as expected, then adds spawns and start to fight. You have to clear these adds first, once you've done this they will go down and gossip option will be available so you can kill them and do the final boss.

Closing this as everything described works.

**Comment by JunkyBulgaria** [comment] 2017-04-15 15:04
TODO: Port this encounter from SAI to C++

**Comment by JunkyBulgaria** [comment] 2017-04-15 15:28
Encounter rewritten from scratch in C++ instead of SmartAI, should work as intended now.

**Comment by Deathtremor** [comment] 2017-04-15 23:22
Re-tested. 

* The only issue i found was that once the group you rescued get down under the pyramid and have a fight with the last group their health wont resets so some of them start fighting only with half of their hp. Screenshots below.

* Also sometimes one mob stays alive and wont run on the top of pyramid. ( Screenshot below)


![wowscrnshot_041617_085602](https://cloud.githubusercontent.com/assets/27430839/25067403/def99b46-2285-11e7-8b3c-1ea7604f1724.jpg)
![wowscrnshot_041617_085606](https://cloud.githubusercontent.com/assets/27430839/25067404/defbbaac-2285-11e7-8e0b-5d2abed1288a.jpg)
![wowscrnshot_041617_085541](https://cloud.githubusercontent.com/assets/27430839/25067405/defff55e-2285-11e7-8955-263b2db673c6.jpg)
![wowscrnshot_041617_090534](https://cloud.githubusercontent.com/assets/27430839/25067416/415cedc4-2286-11e7-9901-76f27a501d0e.jpg)

**Comment by JunkyBulgaria** [comment] 2017-04-17 14:55
1) fix applied
2) needs more testing as i couldn't reproduce it, there was mob but they started tow alk to the bottom

**Comment by Deathtremor** [comment] 2017-04-18 09:02
Re-tested. Confirmed. Everything works fine now,

**Closed** 2017-04-18 09:41 UTC
Labels: Priority: High, Status: Fix Applied, Status: Needs Testing, Target: Core
