### ISSUE TITLE
DK starter quest "the light of dawn" bug

### ISSUE THREAD

**Issue by Nussbaumerli** [FireFly-WoW/FireFly-IssueTracker#395] opened 2017-05-28 21:37 UTC
**Description:**
The final dk quest "the light of dawn" does not end and the battle continues until darion mograine dies.
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Siderbas** [comment] 2017-05-29 01:24
duplicate of #338

**Comment by Shrizz** [comment] 2017-05-29 16:43
I was able to complete this without any issue the other day. Although I remember speaking with someone who described this issue, it doesn't seem to always occur. I'm not sure if it affects anything, but during the battle I died numerous times and killed the NPC who is casting Tranquility constantly, several times (it just respawns instantly so doesn't really matter what you do). The battle ended when I got the enemy force counter down to around 200 and then the RP event began, but I don't remember if it's a timed event or if what you do actually matters in the end.

**Comment by JunkyBulgaria** [comment] 2017-05-30 07:31
needs testing on live, whoever is stuck at this quest please try to do it now, after the counter is done the RP event will start, darion morgaine won't die now

**Comment by JunkyBulgaria** [comment] 2017-05-30 07:36
#338

**Closed by JunkyBulgaria** 2017-05-30 07:36 UTC
Labels: Confirmed, Priority: High, Target: Core
