### ISSUE TITLE
[Dungeon][Bossmechanic][Utgarde Pinnacle] Svala Sorrowgrave

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#328] opened 2017-05-20 14:24 UTC
Current Behavior:

 Ability: [Ritual of the Sword]
Doens't work properly.

She flys into the air but **doesn't** spawn the 3 shades which have to be kiled before letting the sacrifices free.
She also evades in the air which causes a liferegeneration.

How it should work:
https://www.youtube.com/watch?v=9tKsO6U6fVI

**Comment by JunkyBulgaria** [comment] 2017-05-20 23:03
issue 1 is fine, it's from the pre-3.3.5 nerf, it is harder now (working as intended)
issue 2 should be fixed now

**Comment by Soockee** [comment] 2017-05-21 21:54
By bad it. i mean she doenst do the first issue changed. Did it right now and she still doens't do the sacrifice thing

**Comment by JunkyBulgaria** [comment] 2017-05-23 01:14
fix will be applied on ptr soon

**Comment by Demmye** [comment] 2017-05-24 13:04
The encounter in PTR seems completely undoable, since when the boss'es hp hits 20% it teleports few yards above the ground, spawns the shades for a milisecond and then despawns and respawns momentarily.

**Comment by Siderbas** [comment] 2017-05-24 19:34
There is no fix applied yet on the PTR so i will keep it labeled with "Needs Testing"

**Comment by JunkyBulgaria** [comment] 2017-05-24 19:47
encounter partially works so that would suit it better (:

**Comment by Siderbas** [comment] 2017-05-24 19:52
Oh yeah, thought Demmye tested before you applied anything to the PTR yet :D

**Comment by JunkyBulgaria** [comment] 2017-06-24 17:05
evade issue completely fixed, about the 2nd it will work as well now

**Closed** 2017-08-21 00:55 UTC
Labels: Status: Needs Testing
