### ISSUE TITLE
Dungeon Cyanigosa

### ISSUE THREAD

**Issue by Erivanz** [FireFly-WoW/FireFly-IssueTracker#343] opened 2017-05-22 19:21 UTC
**Cyanigosa last Boss of Violet Hold (Heroic):**

Boss dissapears after somewhat 20 seconds

Boss disappears 

Boss shouldnt  disappear 

1. Attack the Boss
2. Wait until she resets
3. ???

**Comment by JunkyBulgaria** [comment] 2017-05-23 00:34
should be fixed with the evade upate

**Comment by Demmye** [comment] 2017-05-24 13:24
Doesn't work on PTR. What I have noticed though, she despawns when she casts [Arcane Vacuum](http://www.wowhead.com/spell=58694/arcane-vacuum) which is most likely the cause of the problem.

**Comment by JunkyBulgaria** [comment] 2017-06-24 17:01
yeah, it was because of this spell, great job!

**Comment by Hardcore-FireFly** [comment] 2017-07-15 08:48
Did VH hrc on live realm a week ago or two. She was working fine.

**Closed** 2017-08-20 15:45 UTC
Labels: Priority: High, PTR / Fix Applied, Status: Tested / Working
