### ISSUE TITLE
[QUEST]

### ISSUE THREAD

**Issue by admitos13** [FireFly-WoW/FireFly-IssueTracker#304] opened 2017-05-14 22:39 UTC
**Description:**

 [Discrediting the Deserters] does not work

**Current behavior:**

When you click to guard and give a talk with them when promoted, nothing happens. Quest does not continue.

**Expected behavior:**

After you speak with guard, some script has to be happening and quest log must give you a sign like 1/6 hand out given

**Steps to reproduce the problem:**

1. Get the quest in  title at theramore island
2. try to speak with a guard where you can promote to the second page

**Screenshots:**

![image](https://cloud.githubusercontent.com/assets/28261869/26037273/9881db5e-38f8-11e7-8213-9dcdc176f358.png)
![image](https://cloud.githubusercontent.com/assets/28261869/26037281/c2a39832-38f8-11e7-8472-46fd568177b5.png)

**Comment by Siderbas** [comment] 2017-05-15 04:54
Duplicate of #241 - needs to be reopened as it seems.

**Comment by JunkyBulgaria** [comment] 2017-05-15 05:41
needs re-testing as they have script

**Comment by TW1NKLET** [comment] 2017-05-15 08:17
> Some of them works, some not due to conditions; see below.
```SQL
--
UPDATE `creature_template` SET `AIName`= 'SmartAI', `ScriptName`= '' WHERE  `entry`=4979;

DELETE FROM `smart_scripts` WHERE `entryorguid` =4979 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(4979,0,0,1,62,0,100,0,8851,0,0,0,81,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - on Gossip option select - set NPC Flags'),
(4979,0,1,2,61,0,100,0,0,0,0,0,72,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - Linked with Previous Event - Close Gossip'),
(4979,0,2,3,61,0,100,0,0,0,0,0,1,0,3000,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - Linked with Previous Event - Say Line 0'),
(4979,0,3,0,61,0,100,0,0,0,0,0,64,1,0,0,0,0,0,7,0,0,0,0,0,0,0,'Theramore Guard - Linked with Previous Event - Store Targetlist'),
(4979,0,4,0,52,0,100,0,0,4979,0,0,11,42725,0,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - Linked with Previous Event - Cast Doctored Leaflet'),
(4979,0,5,6,23,0,100,0,42246,1,121000,121000,1,1,3000,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - On Has Aura Propagandized! - Say Line 1'),
(4979,0,6,0,61,0,100,0,0,0,0,0,33,4979,0,0,0,0,0,12,1,0,0,0,0,0,0,'Theramore Guard - Linked with Previous Event - Give Kill Credit'),
(4979,0,7,8,52,0,100,0,1,4979,0,0,1,2,4000,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - On Text Over Line 1 - Say line 2'),
(4979,0,8,0,61,0,100,0,0,0,0,0,5,11,0,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - Linked with Previous Event - Play Emote ONESHOT_LAUGH'),
(4979,0,9,0,52,0,100,0,2,4979,0,0,81,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Theramore Guard - On Text Over Line 2 - Set NPC Flags');

DELETE FROM `gossip_menu_option` WHERE `menu_id` in(8851);
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `OptionBroadcastTextID`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`, `BoxBroadcastTextID`) VALUES
(8851, 0, 0, 'You look like an intelligent person. Why don''t you read one of these leaflets and give it some thought?', 22549, 1, 1, 21084, 0, 0, 0, NULL, 0);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup` IN(8851);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(15, 8851, 0, 0, 0, 9, 0, 11133, 0, 0, 0, 0, 0, '', 'Gossip Option requires Discrediting the Deserters Taken'),
(15, 8851, 0, 0, 0, 1, 1, 42246, 0, 0, 1, 0, 0, '', 'Gossip Option requires NPC does not have aura Propagandized!');
```

**Comment by TW1NKLET** [comment] 2017-05-15 08:20
> Conditions says the following:

Require aura **Propagandized**
http://www.wowhead.com/spell=42246/propagandized

Require quest taken **Discrediting the Deserters**
http://www.wowhead.com/quest=11133/discrediting-the-deserters

**Comment by Siderbas** [comment] 2017-05-18 05:38
[QA] Testing on PTR now.

**Comment by Siderbas** [comment] 2017-05-18 05:41
Working as intented. Starts a Dialogue and gives quest progression after 2-3secs. Quest completeable.

**Closed** 2017-05-18 16:40 UTC
Labels: Status: Needs Testing
