### ISSUE TITLE
Most range enemies - will run away when approaching during casting or shooting

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#337] opened 2017-05-21 15:26 UTC
As you can see by the title, most monsters that can cast or attack from range will start running quite frequiently when you approach. 

Expected behaviour:
Well they should do atleast by less frequency and stay put abit while casting not running away all the time.
This cause quite a few problems for melees, that have to chase them and can end up with several groups.

**Steps to reproduce the problem:**

1. Find a Range/caster enemy.
2. Attack range/caster enemy.
3. Observe.

**Screenshots:**

I do not have any screenshots, but there is a similiar topic here

- https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/287

**Comment by Siderbas** [comment] 2017-05-21 21:39
Duplicate of #245 - closed.

**Closed by Siderbas** 2017-05-21 21:39 UTC
