### ISSUE TITLE
Quest [Weapons of Destruction]

### ISSUE THREAD

**Issue by Mastertuck** [FireFly-WoW/FireFly-IssueTracker#385] opened 2017-05-27 12:40 UTC
**Description:**

You got to pick up bombs in a camp in scholazar basin.

**Current behaviour:**

Currently only 2 bombs spawn in the camp and the respawn time is over 20 min

**Expected behaviour:**

There should be 8 bombs in the camp, and the respawn rate should be faster.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Siderbas** [comment] 2017-05-27 13:02
Duplicate of #317. Thanks for the report but please use the search function first.

**Closed by Siderbas** 2017-05-27 13:02 UTC
Labels: Invalid - To be Closed
