### ISSUE TITLE
Ahn'kahet: The Old Kingdom(hc)

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#33] opened 2017-04-14 16:23 UTC
**Description:**
Malfunctioning Amanitar&Herald Volazj

CHANGEME: Describe the issue here
Amanitar - does not work mushrooms
Herald Volazj - does not work "Insanity" (but maybe need more ppl in group, idk)

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://wowwiki.wikia.com/wiki/Amanitar
http://wowwiki.wikia.com/wiki/Herald_Volazj

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/2p9y3
http://imgur.com/a/Zy038
url...

**Comment by JunkyBulgaria** [comment] 2017-04-17 14:01
Amanitar - fix applied.
Insanity - works as intended, requires 2+ players

**Comment by Deathtremor** [comment] 2017-04-20 05:47
Re-tested.

* Mushrooms seems to work not properly except one thing.

 "Potent Fungus" buff should be obtainable from Mushroom **ONLY** if "Mini"debuff is **NOT** on the target. - currently you obtain the debuff even tho you have "Mini"debuff on you. 

Source: http://wowwiki.wikia.com/wiki/Amanitar
" _If you kill a healthy mushroom **without the debuff "Mini"** you and anyone nearby gains the buff "Potent Fungus" which grants 100% increased damage._ "

Video: https://youtu.be/j--kwwjgV-0?t=35s ( he kill mushrooms and he dispell "Mini" on him, **however he wont get "Potent Fungus" buff.**

**Comment by JunkyBulgaria** [comment] 2017-04-21 23:15
fix applied for @Deathtremor's point

**Comment by Deathtremor** [comment] 2017-04-22 02:19
Re-tested. Still issues!

Currently not only the **healthy mushroom** wont only dispell "Mini" debuff it they also wont give you Potent Fungus buff if you don't have Mini debuff on you.

**Comment by JunkyBulgaria** [comment] 2017-04-22 21:08
> If you kill a healthy mushroom without the debuff "Mini" you and anyone nearby gains the buff Potent Fungus

**Comment by Deathtremor** [comment] 2017-04-23 02:13
Test it again.

Healthy mushrooms will now remove Mini debuff however he will not cast it on you again once you dispell it with one of the Healthy mushrooms. He is supposed to cast it on you during the whole fight

**Comment by JunkyBulgaria** [comment] 2017-04-25 13:17
killign healthy mushroom now gives the buff as supposed

when you kill healthy and get the curse off, after 15-20s he will cast it again (im not sure about timers as i couldn't find any data for lk)

**Comment by Deathtremor** [comment] 2017-04-26 11:46
@JunkyBulgaria 

Re-tested.

Mushrooms work as they are supposed to.

I'm not really 100% sure if Potent Fungus increase your damage by 100%.  I coudn't re-test again due to ID. Don't have command to restart the boss. 

Please re-test this properly. If it's increases your damage by 100% than it's complately fixed and you can close this!

**Closed** 2017-04-28 15:36 UTC
Labels: Status: Needs Testing, Target: Core
