### ISSUE TITLE
Global pathfinding + LoS

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#335] opened 2017-05-21 12:26 UTC
**Description:**

NPC's through texture, in wrong locations and casters able to attack through hills.

**Current behaviour:**

Pictures are self explanatory

**Screenshots:**

![wowscrnshot_051417_231708](https://cloud.githubusercontent.com/assets/5167458/26283965/cae7afc4-3e39-11e7-94f1-149bf86ff060.jpg)
![wowscrnshot_051417_211721](https://cloud.githubusercontent.com/assets/5167458/26283966/ce18249e-3e39-11e7-8aed-a8cf4a53ed80.jpg)
![wowscrnshot_051417_170638](https://cloud.githubusercontent.com/assets/5167458/26283967/d26d0d48-3e39-11e7-9504-84d88fe368b1.jpg)

**Comment by Siderbas** [comment] 2017-05-21 12:30
Just experienced the same on the live realm, we will look into it. thanks for the report.

**Comment by Erivanz** [comment] 2017-05-22 19:31
[Mob Behaviour] Kiting backwards after casting. #245 fixed it but since a few days its back to where it was before with mobs kiting and running like crazy pls fix

**Comment by l1z1xmd** [comment] 2017-05-23 17:14
Can confirm, that all enemy ranged NPCs are kiting backwards, making them very difficult to kill, especially as melee.

**Comment by JunkyBulgaria** [comment] 2017-05-23 23:14
fixed on ptr, had conflict with previous movement changes, works as intended now

**Comment by Demmye** [comment] 2017-05-24 13:09
It doesn't cast through the walls anymore, but if you kite it around pillar-like objects, they might get stuck and don't move at all, like this: http://i.imgur.com/KvJrrbZ.jpg

**Comment by l1z1xmd** [comment] 2017-05-24 19:23
Enemy ranged NPCs are still kitting backwards (in Ghostlands at least), so no improvement yet.

**Comment by l1z1xmd** [comment] 2017-05-25 17:09
They are not kitting backwards now, but they usually do not follow you when you LoS them.

**Comment by Siderbas** [comment] 2017-05-25 17:12
That's a different open issue @l1z1xmd . #287. Kiting backwards seems so be working now.

**Closed** 2017-05-27 14:38 UTC
Labels: Priority: High, PTR / Fix Applied, Status: Tested / Working
