### ISSUE TITLE
Bugged NPC. quest - Missing diplomat 

### ISSUE THREAD

**Issue by mayumayux** [FireFly-WoW/FireFly-IssueTracker#483] opened 2017-06-08 22:44 UTC
**Description:**

Quest can not be completed. 

**Current behaviour:**
Mob is stuck

**Expected behaviour:**
There should be event with Jaina. 

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/jzOTJ

**Comment by balazskvr** [comment] 2017-06-11 15:08
Duplicate of https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/467

**Closed** 2017-06-24 14:52 UTC
