### ISSUE TITLE
[Get the Key] missing quest item

### ISSUE THREAD

**Issue by iMerdjaoui** [FireFly-WoW/FireFly-IssueTracker#364] opened 2017-05-25 16:45 UTC
Quest name :  [Get the Key]
ID : 12949
NPC to kill to get the key : Intsructor Hroegar
NPC ID : 29915
Tried killing him 3 times, he doesn't drop any loot.

**Comment by Erivanz** [comment] 2017-05-25 17:03
can confirm.

**Comment by Demmye** [comment] 2017-05-26 16:14
Confirmed, the NPC doesn't have any loot table.

**Comment by sarlic1337** [comment] 2017-05-30 12:38
Can still confirm. Not dropping the Item, would set the Priority Medium since there are alot of Followquests depending on this one.

**Comment by sarlic1337** [comment] 2017-06-06 10:36
Can someone pls fix this? Want to to the Quests and its really not much work, it's actual content so shouldn't be priority Low imo

**Comment by thestranger064** [comment] 2017-06-07 13:43
Can confirm, killed twice and nothing. As he said, alot of follow ups after this.
http://imgur.com/a/NqGtW

**Comment by frytik** [comment] 2017-06-07 13:48
I made a fix, should be applied soon.

**Comment by sarlic1337** [comment] 2017-06-24 23:05
Tested on live Realm. 3 Kills no Questitem.

**Comment by JunkyBulgaria** [comment] 2017-06-25 00:25
fix is not applied on live yet

**Comment by warrgazm** [comment] 2017-06-25 03:55
still broken can confirm.

**Comment by warrgazm** [comment] 2017-06-25 03:55
hopefully gets fixed in the Big update whenever that is applyed

**Closed** 2017-08-21 01:04 UTC
Labels: Priority: Low, Status: Needs Testing
