### ISSUE TITLE
walk/run toggle stuck on walk after fighting?

### ISSUE THREAD

**Issue by MINDGAM3** [FireFly-WoW/FireFly-IssueTracker#17] opened 2017-04-14 05:58 UTC
log in and can run around.
get in a fight
afterwards i can only walk
doesnt happen every fight
the walk/run toggle "numpad /" (works before a fight but not when u get stuck walking) 
but i need to log out and log back in to run again.

anyone else getting stuck on walk after being in a fight?

**Comment by MINDGAM3** [comment] 2017-04-14 06:09
i think it maybe after being bashed or stunned i get stuck in walk

**Comment by tjukoela** [comment] 2017-04-14 10:03
I confirm

**Comment by JunkyBulgaria** [comment] 2017-04-14 20:00
Needs testing to confirm if still bugged after today's update.

**Comment by JunkyBulgaria** [comment] 2017-04-14 20:32
closing it as it works as intended, if there are any issues feel free to comment/re-open this issue

**Closed** 2017-04-14 20:31 UTC
Labels: Status: Needs Testing
