### ISSUE TITLE
Zeplin inside deeprun tram 

### ISSUE THREAD

**Issue by admitos13** [FireFly-WoW/FireFly-IssueTracker#220] opened 2017-05-06 16:32 UTC
**Description:**

Zeplin inside deeprun tram on ironforge side

**Current behaviour:**

...

**Expected behaviour:**

no Zepplin inside of tram on the exit of ironforge

![wowscrnshot_050617_192409](https://cloud.githubusercontent.com/assets/28261869/25774152/a13390f6-3292-11e7-8fca-da91946ccf2d.jpg)

**Comment by JunkyBulgaria** [comment] 2017-05-07 00:21
wth

**Comment by JunkyBulgaria** [comment] 2017-05-07 01:28
another player couldn't reproduce it, closing as it is not valid

**Closed by JunkyBulgaria** 2017-05-07 01:28 UTC
Labels: Status: Needs Testing
