### ISSUE TITLE
Herald of War

### ISSUE THREAD

**Issue by Shadoki** [FireFly-WoW/FireFly-IssueTracker#408] opened 2017-05-31 16:52 UTC
**Description:**

Herald of War Quest isnt working as intended.

**Current behaviour:**
So if you complete the herald of war quest, there should be the following quest "battle for undercity" or something named like that, but instead of all this, all NPC's in Undercity in Orgrimmar just despawn.

**Expected behaviour:**
There Should be a following Quest called "Battle for Undercity" or something named like that.

**Comment by Demmye** [comment] 2017-05-31 17:58
Confirmed on PTR, after you complete Herald of War quest (questID=13257), Thrall does not provide you with the next quest of the quest chain A Life Without Regret(questID=13266).

**Comment by Siderbas** [comment] 2017-05-31 18:04
And did NPCs despawn for you aswell?

**Comment by Demmye** [comment] 2017-05-31 18:06
It's not that they despawn, they turn invisible, but I can see them in GM mode.

**Comment by Siderbas** [comment] 2017-05-31 18:10
yeah then they are phased.

**Comment by JunkyBulgaria** [comment] 2017-05-31 18:45
closing as it works as intended, quest was added in 3.3x

**Comment by philoudu16** [comment] 2017-06-01 08:58
If you're basing yourself on what wowhead says for the patch in which the quest was added, beware, because it gives 3.3.0 for just about every quest in northrend, so that data is completely useless.
However if you check comments for both the following quests (http://www.wowhead.com/quest=13266/a-life-without-regret and http://www.wowhead.com/quest=13267/the-battle-for-the-undercity) you will notice most comments are from 3.0.x so I'm 95% sure the quest belongs to 3.0 .

**Comment by JunkyBulgaria** [comment] 2017-06-01 12:45
this quest was added with the icc release and undercity's fall under putress's attack

**Comment by Siderbas** [comment] 2017-06-06 08:27
Yes but players shouldn't be stuck in a phase without npcs in orgrimmar or undercity

**Comment by philoudu16** [comment] 2017-06-07 16:50
This quest was not added in 3.3, that may be what wowhead says, but it says it for all the quests in Northrend. If you check the comments you'll see they date back from 3.0.x.
Also this video dates back from before 3.0.2 was even released (i guess he was on the PTR):
https://www.youtube.com/watch?v=cqvnd_1aleY

**Comment by philoudu16** [comment] 2017-06-25 13:32
Doesn't seem to be fixed on PTR (my toon is in the phased Orgrimmar but still no Thrall to give me the following quest)

**Closed** 2017-07-07 16:53 UTC
Labels: Priority: High, Status: Needs Testing
